# Generated by Django 3.1.7 on 2021-06-08 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulot Nomi')),
                ('photo', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0, verbose_name='Narxi')),
                ('description', models.TextField(verbose_name='Mahzulot haqida izoh')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.category', verbose_name='Mahsulot Turi')),
            ],
        ),
    ]
