# Generated by Django 3.1.7 on 2021-06-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='product',
        ),
    ]
