# Generated by Django 3.1.7 on 2021-06-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_auto_20210608_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='incart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulot Nomi')),
                ('photo', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0, verbose_name='Narxi')),
                ('description', models.TextField(verbose_name='Mahzulot haqida izoh')),
            ],
        ),
    ]
