# Generated by Django 3.1.7 on 2021-06-08 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_incart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incart',
            name='description',
        ),
        migrations.RemoveField(
            model_name='incart',
            name='name',
        ),
        migrations.RemoveField(
            model_name='incart',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='incart',
            name='price',
        ),
        migrations.AddField(
            model_name='incart',
            name='choise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='one.product'),
            preserve_default=False,
        ),
    ]
