# Generated by Django 3.1.7 on 2021-06-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0004_auto_20210608_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='incart',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Soni'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Soni'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, verbose_name='Narxi'),
        ),
    ]
