# Generated by Django 3.1.7 on 2021-06-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0005_auto_20210609_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incart',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Soni'),
        ),
    ]
